require("fran")
print("Welcome Fran")

vim.keymap.set('n', 'f', 'e', { noremap = true })
vim.keymap.set('n', 'p', 'r', { noremap = true })
vim.keymap.set('n', 'b', 't', { noremap = true })
vim.keymap.set('n', 'j', 'y', { noremap = true })
vim.keymap.set('n', 'l', 'u', { noremap = true })
vim.keymap.set('n', 'u', 'i', { noremap = true })
vim.keymap.set('n', 'y', 'o', { noremap = true })
vim.keymap.set('n', ';', 'p', { noremap = true })
vim.keymap.set('n', 'r', 's', { noremap = true })
vim.keymap.set('n', 's', 'd', { noremap = true })
vim.keymap.set('n', 't', 'f', { noremap = true })
vim.keymap.set('n', 'm', 'h', { noremap = true })
vim.keymap.set('n', 'n', 'j', { noremap = true })
vim.keymap.set('n', 'e', 'k', { noremap = true })
vim.keymap.set('n', 'i', 'l', { noremap = true })
vim.keymap.set('n', 'o', ';', { noremap = true })
vim.keymap.set('n', 'x', 'z', { noremap = true })
vim.keymap.set('n', 'c', 'x', { noremap = true })
vim.keymap.set('n', 'd', 'c', { noremap = true })
vim.keymap.set('n', '`', 'b', { noremap = true })
vim.keymap.set('n', 'k', 'n', { noremap = true })
vim.keymap.set('n', 'h', 'm', { noremap = true })

vim.keymap.set('n', 'F', 'E', { noremap = true })
vim.keymap.set('n', 'P', 'R', { noremap = true })
vim.keymap.set('n', 'B', 'T', { noremap = true })
vim.keymap.set('n', 'J', 'Y', { noremap = true })
vim.keymap.set('n', 'L', 'U', { noremap = true })
vim.keymap.set('n', 'U', 'I', { noremap = true })
vim.keymap.set('n', 'Y', 'O', { noremap = true })
vim.keymap.set('n', ';', 'P', { noremap = true })
vim.keymap.set('n', 'R', 'S', { noremap = true })
vim.keymap.set('n', 'S', 'D', { noremap = true })
vim.keymap.set('n', 'T', 'F', { noremap = true })
vim.keymap.set('n', 'M', 'H', { noremap = true })
vim.keymap.set('n', 'N', 'J', { noremap = true })
vim.keymap.set('n', 'E', 'K', { noremap = true })
vim.keymap.set('n', 'I', 'L', { noremap = true })
vim.keymap.set('n', 'O', ';', { noremap = true })
vim.keymap.set('n', 'X', 'Z', { noremap = true })
vim.keymap.set('n', 'C', 'X', { noremap = true })
vim.keymap.set('n', 'D', 'C', { noremap = true })
vim.keymap.set('n', '`', 'B', { noremap = true })
vim.keymap.set('n', 'K', 'N', { noremap = true })
vim.keymap.set('n', 'H', 'M', { noremap = true })
